### ISSUE TITLE
New integrations

### ISSUE THREAD

**Issue by ameicler** [ridereceipts/ridereceipts#6]
Congrats for the great work!

Any plans on integrating new subscriptions? Other VTC companies (Txfy, Chauffeur Privé, etc.) or other services (Deliveroo, etc.)?

**Comment by mrgodhani** [comment]
@ameicler Thanks for your message. At this time we are focusing on Uber and Lyft since these are the biggest companies in the ride share industry. We are from Canada and some of those services you mentioned are not available to use. If we get help/more feedback that would be great. Feedback gives us idea what we can improve and work on future integrations and features.

**Comment by michael2france** [comment]
@mrgodhani 
VTC is the french official acronym for Private Hire Vehicule (UK) : the sub industry of registered and professional riders in ride share industry. 

Taxify is a 1B$ startup based in Estonia, sponsored by Daimler (owner of Mercedes brand, Freightliner trucks & more - Dutch) Didi (winner competitor of Uber - China) & more and a rising competitor to Uber's second markets in the world, available in Toronto. 

Chauffeur Privé is french (owned by Daimler - Dutch) & the main competitor to Uber in France where it only operates. 

Deliveroo is a 800M$ startup based in United Kingdom, a competitor to UberEat & Foodora in Europe where it mainly operates, but also available in Hong Kong, Singapore, United Arab Emirates and Australia.

**Comment by mrgodhani** [comment]
Will close this issue since now we have feedback section #7
